[theme]
primaryColor = "#9B72CB"
backgroundColor = "#F8F7FA"
secondaryBackgroundColor = "#ffffff"
textColor = "#1D1B2A"
font = "sans serif"

[server]
runOnSave = true
enableCORS = false

[client]
showErrorDetails = false